apiVersion: v1
kind: LimitRange
metadata:
  name: aismv
  namespace: aismv
spec:
  limits:
  - max:
      cpu: "1"
      memory: "2Gi"
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "100Mi"
    type: Container
