apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "1000m"
      memory: "2Gi"
    default:
      cpu: "500m"
      memory: "1Gi"
    type: Container
